Resources:
  GitHostname:
    Type: AWS:SSM:Parameter
    Properties:
      Name: /burkcules/oauth/${self:provider.stage}/GIT_HOSTNAME
      Description: Hostname for the authentication provider
      Tier: Standard
      Type: String
      Value: ${env:GIT_HOSTNAME}

  OauthTokenPath:
    Type: AWS:SSM:Parameter
    Properties:
      Name: /burkcules/oauth/${self:provider.stage}/OAUTH_TOKEN_PATH
      Description: Token Api Uri path
      Tier: Standard
      Type: String
      Value: ${env:OAUTH_TOKEN_PATH}

  OauthAuthorizePath:
    Type: AWS:SSM:Parameter
    Properties:
      Name: /burkcules/oauth/${self:provider.stage}/OAUTH_AUTHORIZE_PATH
      Description: Authorize Api Uri path
      Tier: Standard
      Type: String
      Value: ${env:OAUTH_AUTHORIZE_PATH}

  OauthClientId:
    Type: AWS:SSM:Parameter
    Properties:
      Name: /burkcules/oauth/${self:provider.stage}/OAUTH_CLIENT_ID
      Description: Github OAuth Client Id
      Tier: Standard
      Type: String
      Value: ${env:OAUTH_CLIENT_ID}

  OauthClientSecret:
    Type: AWS:SSM:Parameter
    Properties:
      Name: /burkcules/oauth/${self:provider.stage}/OAUTH_CLIENT_SECRET
      Description: Github OAuth Client Secret
      Tier: Standard
      Type: String
      Value: ${env:OAUTH_CLIENT_SECRET}

  RedirectUrl:
    Type: AWS:SSM:Parameter
    Properties:
      Name: /burkcules/oauth/${self:provider.stage}/REDIRECT_URL
      Description: Callback Url in API Gateway
      Tier: Standard
      Type: String
      Value: ${env:REDIRECT_URL}

  OauthScopes:
    Type: AWS:SSM:Parameter
    Properties:
      Name: /burkcules/oauth/${self:provider.stage}/OAUTH_SCOPES
      Description: OAuth Scopes
      Tier: Standard
      Type: String
      Value: ${env:OAUTH_SCOPES}